/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.curso.dao.br.com.ifba.view;
import br.com.ifba.curso.dao.CursoDao;
import br.com.ifba.curso.dao.CursoIDao;
import javax.swing.JOptionPane;
import br.com.ifba.curso.entity.Curso;
import br.com.ifba.service.CursoIService;
import br.com.ifba.service.CursoService;
import java.util.List;



/**
 *
 * @author ketli
 */
public class TelaPrincipal extends javax.swing.JFrame { // Define a janela principal (a primeira tela que o usuário vê).
    
   
    private final CursoIService cursoService = new CursoService(); // Instância do Service (Camada de Regra de Negócio) para interagir com o banco.
    private final CursoDao cursoDao = new CursoDao(); // Instância do DAO (Camada de Acesso ao Banco).
    
    // Inicializa a tela.
    public TelaPrincipal() {
        initComponents(); // Monta os componentes visuais (botões, campo de texto, área de listagem, etc.).
        carregarCursos(); // Chama a função para buscar e listar os cursos assim que a tela é aberta.
    }
    
    // Responsável por buscar todos os cursos e exibir na tela.
    public void carregarCursos(){
        try{
            //Pede ao Service para buscar todos os cursos no banco de dados.
            List<Curso> cursos = cursoService.findAll(); 
            // Objeto usado para construir o texto que será exibido de forma eficiente.
            StringBuilder sb = new StringBuilder(); 
            
            //Checa se a lista de cursos veio vazia.
            if(cursos.isEmpty()){
                sb.append("Nenhum curso cadastrado");
            }else{
                // 3. FORMATAÇÃO: Percorre a lista de cursos.
                for(Curso c: cursos){
                    // Constrói uma linha formatada (ID | Nome | Qtd) para cada curso.
                    sb.append("ID: ").append(c.getId())
                    .append(" | Nome: ").append(c.getNome() != null ? c.getNome() : "N/A") // Tratamento simples se o Nome for nulo.
                    .append(" | Qtd: ").append(c.getQuantidade() != 0 ? c.getQuantidade() : "N/A") // Tratamento simples se a Qtd for zero.
                    .append("\n"); // Adiciona uma quebra de linha.
                }
            }
            //Coloca o texto formatado (sb) na área de texto da tela (txtListar).
            txtListar.setText(sb.toString()); 
            
        }catch (Exception e) {
            //Bloco de tratamento de erro se houver falha na comunicação com o Service/Banco.
            txtListar.setText("Erro ao carregar cursos: " + e.getMessage());
            JOptionPane.showMessageDialog(this, "Erro ao carregar cursos: " + e.getMessage(), "Erro de Persistência", JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtListar = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Cursos Adicionados:");

        txtListar.setColumns(20);
        txtListar.setRows(5);
        txtListar.setEnabled(false);
        jScrollPane1.setViewportView(txtListar);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Buscar por ID:");

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Excluir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Cadastrar novo Curso");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Editar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(643, 643, 643)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(31, 31, 31)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(34, 34, 34)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try{ 
            Long id = Long.valueOf(txtID.getText());//Pega o ID informado na caixa
            Curso curso = cursoService.findById(id); //faz a buscar no ID usando o cursoService
            
            if(curso != null){//Imprime as informações do ID se encontrar
                String resultado = "CURSO ENCONTRADO:\n" + "ID:" + curso.getId()+
                        "| Nome: " + curso.getNome() + "\n" + "| QTD: " + curso.getQuantidade() +
                        "| Descrição: " + curso.getDescricao();
                
                JOptionPane.showMessageDialog(this, resultado, "Busca por ID", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (NumberFormatException e) {//Tratamento de exceções
        JOptionPane.showMessageDialog(this, "Por favor, insira um ID numérico válido.", "Erro de Entrada", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro ao buscar curso: " + e.getMessage(), "Erro de Persistência", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Cria a nova janela de cadastro, passando 'this' (a referência da TelaPrincipal).
        // Isso permite que a TelaCadastro saiba qual tela principal deve ser atualizada.
        TelaCadastro telaCadastro = new TelaCadastro(this);
        
        // Adiciona um 'ouvinte' (Listener) para monitorar eventos na janela de cadastro.
        telaCadastro.addWindowListener(new java.awt.event.WindowAdapter() {
            
            @Override//Este método é chamado automaticamente ASSIM QUE a janela de cadastro é fechada (Dispose).
            public void windowClosed(java.awt.event.WindowEvent windowEvent){
                // Recarrega a lista de cursos na TelaPrincipal.
                // Isso garante que o curso recém-cadastrado/editado apareça imediatamente.
                carregarCursos();
            }
        });
        
        telaCadastro.setVisible(true);
        

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{//Ação para excluir um cadastro
            Long id = Long.parseLong(txtID.getText().trim());//Recebe ID
                
            Curso cursoParaExcluir = cursoDao.findById(id); //faz a busca pelo ID e transfere para cursoParaExcluir
                
            
                if(cursoParaExcluir != null){
                    int confirmacao = JOptionPane.showConfirmDialog(this, "Certeza que deseja excluir o curso ID: " + id + "?",
                        "Confirmar Exclusão", JOptionPane.YES_NO_OPTION);//faz a confirmação com o usuario
                    
                if(confirmacao == JOptionPane.YES_OPTION){
                    cursoDao.delete(cursoParaExcluir);
                    JOptionPane.showMessageDialog(this, "Curso com ID " + id + "Excluido com sucesso!");
                    carregarCursos();
                    txtID.setText("");                 
                }

            }else{
                    JOptionPane.showMessageDialog(this, "Curso com id: "+ id + "não encontrado");
                }      
                //Tratamento de exceçoes
        }catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Por favor, digite um ID numérico válido.", "Erro de Entrada", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erro ao excluir: " + e.getMessage(), "Erro de Banco de Dados", JOptionPane.ERROR_MESSAGE);
        }


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try{
            Long id = Long.parseLong(txtID.getText().trim());
            
            Curso curso = cursoDao.findById(id);
            
            if(curso !=null){
               String detalhes = String.format("ID: %d\nNome: %s\nQtd: %d\nDescrição: %s\nFornecedor: %s",
                curso.getId(), curso.getNome(), curso.getQuantidade(), curso.getDescricao(), curso.getFornecedor());
               
               JOptionPane.showMessageDialog(this, detalhes, "Detalhes do Curso ID: " + id, JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(this, "Curso com ID " + id + " não encontrado.", "Busca Vazia", JOptionPane.WARNING_MESSAGE);
        
            }
                       
        }catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Por favor, digite um ID numérico válido para buscar.", "Erro de Entrada", JOptionPane.ERROR_MESSAGE);
    }


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line a   rguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextArea txtListar;
    // End of variables declaration//GEN-END:variables
}
